name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pushd node_vm2/vm-server && npm install && popd
      - run: pip install -U pip
      - run: pip install -r requirements-lock.txt
      - run: pip install .
      - run: python cute.py test
