name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.x'
      - run: pip install -U pip
      - run: pip --version
      - run: cat pyproject.toml || exit 0
      - run: cat setup.py || exit 0
      - run: pip install -r requirements-lock.txt
      - run: pip show setuptools
      - run: pip install .
      - run: python cute.py test
